# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c2c9cb8b3c5529f1117540eaa6dbeba1bb0194193b273802a5cc9b8aa950b340566e191d23e1292f6092d84b5d486336c2ccd9cbb46c26603a833a1c52e14ce

test:
  secret_key_base: a473a2005f3c3befeab9e96a0660a9313516fe7578ddc44350360a0c9b972983fc150289f3ed2478ff7e6ce1e5fad79b12be009f3470772400aa43f66a177cac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
